theme: jekyll-theme-minimal
title: Catherine Tsaowimonsiri System Administration Documentation
description: Project Documentation Links:<p><a href="archlinux.html">Project 1- Arch Linux Installation</a><p><a href="wireguard.html">Project 3- WireGuard Lab</a>
